### ISSUE TITLE
Directory of Australian quantitative ecologists

### ISSUE THREAD

**Issue by dfalster** [esa-qerc/website#7]
Throwing this idea out there -- should we add a directory page where members can list their name and research interests? Perhaps limit to keywords and weblink for page?

Challenge is maintaining this in a way that doesn't get out of date. A link to linked in, or other web profile maybe be better than institution?

**Comment by jdyen** [comment]
What would be the main goal of this? To connect us as ecologists? Or to advertise our skills to others?

Definitely a challenge to keep these sorts of things up to date, particularly given high turnover of ECRs.

**Comment by dfalster** [comment]
What's your thoughts about this  @jdyen @goldingn having now looked at survey form?

**Comment by jdyen** [comment]
I'm still not convinced we need it. If we're doing away with the idea of formal "membership", it's hard to do something like this without maintaining a database of active quant-ecologists.

Alternatively, could find a way to automatically update this table from a form (easy to add people, harder to edit or remove without admin intervention).

**Comment by dfalster** [comment]
Agreed, we don't want high maintenance site. 

I was thinking we would have a spreadsheet of notional members somewhere. The webpage would then be autogenerated form the info in that spreadsheet. Ideally spreadsheet is designed so that when anyone fills out the signup form, the relevant details are captured and added. We're already starting that process with the information collected in the from we have prepared for circulation (later today probably). Updating the website would be relatively straightforward then

**Comment by jdyen** [comment]
I'm OK with that approach. Updating is easy if we're just adding people -- it will be more challenging to remove people or edit their details with that approach.

**Comment by dfalster** [comment]
if we start with that, we can see how useful the site it. If not so much, we can disband before having to delete anyone.

**Comment by goldingn** [comment]
From our meeting just now, I think the plan is:

 - set up a 'member profiles' page
 - add members from the survey, with name, interests, and favicon links for twitter, github, website etc. 
 - add details on how to edit/add to the listing via a pull request (or to email us with content if they aren't comfortable with GitHub)

Sound about right?

**Comment by jdyen** [comment]
Sounds good, except I would give people an option to redact things from their survey responses. I think the survey made it clear that their details would be made public, but not everyone reads things properly. I like the idea of PRs -- will be keen to see how many people take it up who aren't already familiar with GH.

**Comment by dfalster** [comment]
Sounds good. Perhaps also an alternative route for those who don't use GitHub, e.g. google form that collects all the right fields? 

Here's an idea - we could set up the website to build from info in a google spreadsheet, then any responses from the survey would go straight in and be automatically incorporated on next build?

**Comment by goldingn** [comment]
That would be good, if you are volunteering to write the script :)

The icon links turned out to be a surprising pain in the arse, but should have an example working soon.

**Comment by goldingn** [comment]
I was thinking of just adding the names and interests from the survey, but it would be good to request the info again from those people, with guidance on how to specify interests (ie. as a list, not a paragraph) along with usernames for twitter, Facebook, GitHub, and a website URL

**Comment by goldingn** [comment]
A downside to a Google Doc is that there's no control over edits (people could add obscenities, or edit others' details), which I think would be important given it's a public website and we have a responsibility to curate it. We could request details via a Google Form, then manually copy over to the doc for syncing. But that doesn't save us that much maintenance cf. pull requests

**Comment by goldingn** [comment]
OK, I've pushed up a branch `member_profiles`, which has the page and instructions on the readme for how to update a profile: https://github.com/esa-qerc/website/tree/member_profiles#edit-profile

That's in the banner like this:
![Screen Shot 2019-08-02 at 2 08 28 pm](https://user-images.githubusercontent.com/4450731/62343882-2a57d380-b52f-11e9-80c1-529c471bfd86.png)

And the page looks like this:
![Screen Shot 2019-08-02 at 2 08 43 pm](https://user-images.githubusercontent.com/4450731/62343887-2d52c400-b52f-11e9-888c-848417857a5b.png)

The icons open to links in new tabs. There's not much styling we can do to this without a huge amount of extra work.

The markdown (with custom hugo shortcodes) for each entry looks like this:

```
## Nick Golding
 
{{< twitter _nickgolding_ >}}
{{< github goldingn >}}
{{< website "https://scholar.google.co.uk/citations?user=peoal7wAAAAJ&hl=en" >}}

Statistical Ecology, Research Software, Public Health
```

(Facebook link is also available, but I don't have one)

So it wouldn't be too hard to build that page with a script reading from a google doc, and execute that script in [the website deploy script](https://github.com/esa-qerc/website/blob/member_profiles/deploy.sh) though we'd need a human step to make sure the entries are safe to share

**Comment by jdyen** [comment]
I opened a PR with my edits. Works for me.

**Comment by dfalster** [comment]
Nice, thanks Nick! I also opened a PR with my edits

Following above discussions, seems we can't avoid a human step if enabling a GitHub alternative. So not convinced about the google doc option. Suggest leaving for now.

Shall I generate material for those who indicated they'd like to be included from the survey? I'd suggest making it from what we have, then edit based on feedback (if needed)

**Comment by jdyen** [comment]
The google doc and script could take care of all the annyoing bits, then we just scan and commit.

And yes to using survey for that. It did ask "can we put this info on the website?" in a question.

**Comment by goldingn** [comment]
Yes, a PR with material for the 'yes's in the survey would be great, thanks!

**Comment by goldingn** [comment]
For future reference, here's the script I used to format the google sheet into the templated markdown of member profiles:

```r
library(googlesheets)
library(glue)

# the data are in a private sheet. This will force you to authenticate:
sheet <- gs_key("1UJSGGzd1_aP8gGsJiqt8mgVESYlLhrpNb7qiSn3uXQM",
                visibility = "private")
df <- gs_read(sheet)

# subset to those who want a profile on the website
want_membership <- df$`Would you like to be considered a member of the Australian QERC?` == "Yes"
want_profile <- df$`Would you like a short profile of you listed on our webpage, created from the information you listed above?` == "Yes"
keep <- want_membership & want_profile
df <- df[keep, ]

# rename for convenience
df <- data.frame(name = df$`What is your name?`,
                 twitter = df$`Do you have a twitter handle?`,
                 website = df$`Link to personal profile (Webpage, linkedIn, or other)`,
                 focus = df$`Two sentences about your research interests`)

# sanitise names and handles
df$name <- tools::toTitleCase(as.character(df$name))
df$twitter <- gsub("@", "", df$twitter)

template <- "
## [name]

{{< twitter [twitter] >}}
{{< website \"[website]\" >}}

[focus]

---

"

content <- glue::glue_data(df, template, .na = "", .open = "[", .close = "]")

# sanitise missing links
content <- gsub("\\{\\{< twitter  >\\}\\}\n", "", content)
content <- gsub("\\{\\{< website \"\" >\\}\\}\n", "", content)

# this still needs some manual editing to fill in some missing surnames

content

```
